import React from "react";

import "./PrivacyPolicy.css";

function PrivacyPolicy() {
  return (
    <div className="privacy-policy-section">
      <div className="privacy-policy-main-section">
        <div className="privacy-policy-heading">
          <h2>Privacy Policy</h2>
        </div>
        <div className="privacy-policy-main-content">
          <div className="privacy-policy-para-container">
            <h3></h3>
            <p>
              This Privacy Policy outlines our practices and procedures
              concerning the gathering, usage, and disclosure of your
              information when you utilize our services. It also clarifies your
              privacy rights and how the law safeguards your data.
            </p>
            <p>
              We use your personal data to provide and enhance our services. By
              using our services, you consent to the collection and use of
              information as described in this Privacy Policy. Please note that
              this Privacy Policy has been generated with the assistance of a
              Privacy Policy Generator.
            </p>
          </div>
          <h3>Interpretation and Definitions</h3>
          <div className="privacy-policy-para-container">
            <h3>Interpretation:</h3>
            <p>
              Words starting with a capital letter have specific definitions as
              outlined below. These definitions hold whether the words are
              singular or plural.
            </p>
          </div>
          <div className="privacy-policy-para-container">
            <h3>Definitions:</h3>
            <h4>For the purposes of this Privacy Policy:</h4>
            <p>
              Account refers to a unique account established for you to access
              our service or specific service components.
            </p>
            <p>
              Company (referred to as "the Company," "We," "Us," or "Our" in
              this Agreement) pertains to Lumineux Properties.
            </p>
            <p>
              Cookies are small files placed on your computer, mobile device, or
              other devices by a website. They contain details about your
              browsing history on that website, among other uses.
            </p>
            <h4>
              <b>Country refers to the United Arab Emirates.</b>
            </h4>
            <p>
              Device signifies any apparatus capable of accessing the service,
              such as a computer, cellphone, or digital tablet.
            </p>
            <p>
              Personal Data encompasses information related to an identified or
              identifiable individual.
            </p>
            <p>Service relates to the website.</p>
            <p>
              Service Provider stands for any natural or legal entity that
              processes data on behalf of the Company. This term refers to
              third-party companies or individuals employed by the Company to
              facilitate the Service, provide the Service on the Company's
              behalf, offer services related to the Service, or assist the
              Company in analyzing how the Service is utilized.
            </p>
            <p>
              Usage Data pertains to data collected automatically, either
              generated by using the Service or from the Service infrastructure
              itself (e.g., page visit duration).
            </p>
            <p>
              Website designates Lumineux Properties, accessible from [website
              link].
            </p>
            <p>
              You represents the individual using or accessing the Service, or
              the company or legal entity on whose behalf such an individual
              accesses or uses the Service.
            </p>
          </div>
          <h3>Collecting and Using Your Personal Data</h3>
          <h4>Types of Data Collected</h4>
          <div className="privacy-policy-para-container">
            <h3>Personal Data:</h3>
            <p>
              While using our service, we may request specific personally
              identifiable information that can be employed to contact or
              identify you. This information may encompass, but is not
              restricted to:
              <ul>
                <li>Email address</li>
                <li>First name and last name</li>
                <li>Phone number</li>
                <li>
                  Usage Data:
                  <p>
                    Usage Data is collected automatically when using our
                    Service. It may include information like your Device's
                    Internet Protocol address, browser type, the pages you visit
                    on our Service, time and date of your visits, time spent on
                    those pages, unique device identifiers, and other diagnostic
                    data.
                  </p>
                </li>
              </ul>
            </p>
            <p>
              When you access our Service via a mobile device, we may
              automatically collect certain information, including the type of
              mobile device you use, its unique ID, the IP address of your
              mobile device, your mobile operating system, the type of mobile
              Internet browser you use, unique device identifiers, and
              additional diagnostic data. We might also collect information your
              browser sends when you visit our Service or access it through a
              mobile device.
            </p>
          </div>
          <div className="privacy-policy-para-container">
            <h3>Tracking Technologies and Cookies:</h3>
            <p>
              We use cookies and similar tracking technologies to monitor and
              store specific information, enhancing and analyzing our Service.
              These technologies can encompass beacons, tags, and scripts used
              to collect and track data.
            </p>
            <p>
              Cookies can be categorized as "Persistent" or "Session" Cookies.
              Persistent Cookies remain on your personal computer or mobile
              device after you go offline, whereas Session Cookies are deleted
              when you close your web browser.
            </p>
            <p>
              Our Service may use both Session and Persistent Cookies for
              various purposes, such as necessary, functionality, and cookies
              policy acceptance. For more information on the cookies we use and
              your options regarding cookies, please refer to our Cookies
              Policy.
            </p>
          </div>
          <div className="privacy-policy-para-container">
            <h3>Use of Your Personal Data:</h3>
            <p>
              We may use your Personal Data for multiple purposes, including but
              not limited to:
              <ul>
                <li>
                  Providing and maintaining our Service, including monitoring
                  its usage.
                </li>
                <li>
                  Managing your Account, offering you access to specific
                  features available to registered users.
                </li>
                <li>
                  Fulfilling contracts, such as product or service purchase
                  agreements.
                </li>
                <li>
                  Contacting you for updates, security alerts, and informative
                  communications.
                </li>
                <li>
                  Providing news, special offers, and general information
                  related to goods, services, and events similar to those you've
                  already purchased or inquired about.
                </li>
                <li>Managing your requests and inquiries.</li>
                <li>
                  Evaluating or conducting business transfers, including
                  mergers, sales of company assets, or acquisitions.
                </li>
                <li>
                  Analyzing data, identifying usage trends, and improving our
                  Service, products, services, marketing, and user experience.
                </li>
              </ul>
            </p>
          </div>
          <div className="privacy-policy-para-container">
            <h3>Disclosure of Your Personal Data:</h3>
            <p>
              <ul>
                <li>
                  Service Providers: We may share your personal data with
                  Service Providers to monitor and analyze our Service usage and
                  to contact you.
                </li>
                <li>
                  Business Transfers: If the Company is involved in a merger,
                  acquisition, or asset sale, your Personal Data may be
                  transferred. We will provide notice before your Personal Data
                  is transferred and becomes subject to a different Privacy
                  Policy.
                </li>
                <li>
                  Affiliates: We may share your data with our affiliates,
                  requiring them to comply with this Privacy Policy.
                </li>
                <li>
                  Business Partners: We may share your information with business
                  partners to provide you with certain products, services, or
                  promotions.
                </li>
                <li>
                  Other Users: Information shared in public areas with other
                  users may be viewed and distributed publicly.
                </li>
                <li>
                  Your Consent: We may disclose your personal information for
                  other purposes with your consent.
                </li>
              </ul>
            </p>
          </div>
          <div className="privacy-policy-para-container">
            <h3>Retention of Your Personal Data:</h3>
            <p>
              We will retain your Personal Data for as long as necessary for the
              purposes set out in this Privacy Policy. Usage Data may be
              retained for internal analysis purposes, with retention periods
              varying.
            </p>
          </div>
          <div className="privacy-policy-para-container">
            <h3>Transfer of Your Personal Data:</h3>
            <p>
              Your information, including Personal Data, may be processed at the
              Company's operating offices or other locations where data
              processing parties are situated. This may involve transferring
              this information to computers outside your jurisdiction. The
              Company will take all reasonably necessary steps to ensure your
              data's security and adherence to this Privacy Policy during
              transfer.
            </p>
          </div>
          <div className="privacy-policy-para-container">
            <h3>Disclosure of Your Personal Data:</h3>
            <p>
              <ul>
                <li>
                  Business Transactions: If the Company participates in a
                  merger, acquisition, or asset sale, your Personal Data may be
                  transferred. We will inform you before your Personal Data is
                  transferred and subject to a different Privacy Policy.
                </li>
                <li>
                  Law Enforcement: In specific circumstances, the Company may
                  disclose your Personal Data if mandated by law or in response
                  to valid requests from public authorities (e.g., a court or
                  government agency).
                </li>
                <li>
                  Other Legal Requirements: The Company may disclose your
                  Personal Data in good faith when necessary to comply with
                  legal obligations, protect rights, or investigate possible
                  wrongdoing.
                </li>
              </ul>
            </p>
          </div>
          <div className="privacy-policy-para-container">
            <h3>Security of Your Personal Data:</h3>
            <p>
              While we make efforts to use commercially accepted means to
              safeguard your Personal Data, no method of data transmission over
              the Internet or electronic storage can guarantee 100% security.
            </p>
          </div>
          <div className="privacy-policy-para-container">
            <h3>Children’s Privacy:</h3>
            <p>
              Our Service is not intended for individuals under the age of 13.
              We do not knowingly collect personally identifiable information
              from those under 13. If you are a parent or guardian and realize
              that your child has provided Personal Data, please Contact Us. If
              we discover that we have collected Personal Data from individuals
              under 13 without parental consent verification, we will take steps
              to remove this information from our servers.
            </p>
          </div>
          <div className="privacy-policy-para-container">
            <h3>Links to Other Websites:</h3>
            <p>
              Our Service may contain links to other websites not operated by
              Us. We encourage you to review the Privacy Policy of each site you
              visit. We have no control over the content, privacy policies, or
              practices of those sites.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}

export default PrivacyPolicy;
